# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Additional RuboCop extensions
plugins:
  - rubocop-rspec
  - rubocop-rspec_rails

# Overwrite or add rules to create your own house style
inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  StyleGuideCopsOnly: false

# Basic style configurations
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

# Basic metrics configurations
Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 5

# RSpec configurations
RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/MessageSpies:
  EnforcedStyle: receive

# RSpec Rails configurations
RSpecRails/InferredSpecType:
  Enabled: false
